#   SCE CONFIDENTIAL                                      
#   PlayStation(R)3 Programmer Tool Runtime Library 370.001
#   Copyright (C) 2007 Sony Computer Entertainment Inc.   
#   All Rights Reserved. 

CELL_SDK ?= /usr/local/cell
CELL_SAMPLE_DIR ?= $(CELL_SDK)/samples
CELL_MK_DIR ?= $(CELL_SAMPLE_DIR)/mk
include $(CELL_MK_DIR)/sdk.makedef.mk

MK_TARGET = tinyxml.mk 

include $(CELL_MK_DIR)/sdk.target.mk

